/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.Desktop;

import Crops.Crop;
import Crops.SetOfCrops;
import Fields.Field;
import Users.Farmer;
import Users.setOfUsers;
import Fields.SetOfFields;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eranga
 */
public class FieldManagement extends javax.swing.JFrame {

    setOfUsers sou = new setOfUsers();
    SetOfCrops soc = new SetOfCrops();
    SetOfFields sof = new SetOfFields();

    /**
     * Creates new form FieldManagement
     */
    public FieldManagement() {
        try {
            initComponents();
            sou.deserialize();
            soc.deserialize();
            sof.deSerialize();
            fieldTableLoad(sof, jTable1, jScrollPane1);
            fieldTableLoad(sof, jTable2, jScrollPane2);
            fieldTableLoad(sof, jTable3, jScrollPane3);
            
            //Vector<Farmer> far = sou.getAllFarmers();
            for (Farmer fm : sou.getAllFarmers()) {
                jComboBox1.addItem("" + fm.getUserId());
            }
            for (Crop cp : soc) {
                jComboBox2.addItem("" + cp.getCropID());
            }
        } catch (Exception ex) {
        }
    }

    public void fieldTableLoad(SetOfFields sf, JTable table, JScrollPane pane) {
        Vector tmp = new Vector<>();

        for (Field item : sf) {
            Vector row = new Vector();
            row.addElement(item.getFieldID());
            row.addElement(item.getLocation());
            row.addElement(item.getLontitude());
            row.addElement(item.getLatitude());
            row.addElement(item.getOwner().getName());
            row.addElement(item.getCrop().getName());

            tmp.add(row);
        }

        //set column headings
        Vector columnNames = new Vector();
        columnNames.addElement("Field ID");
        columnNames.addElement("Location");
        columnNames.addElement("Longitude");
        columnNames.addElement("Lattitude");
        columnNames.addElement("Owner");
        columnNames.addElement("Crop");
        //set table model
        DefaultTableModel model = new DefaultTableModel(tmp, columnNames);

        table.setModel(model);
        pane.setViewportView(table);
        table.setAutoscrolls(true);
        table.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AddSensor = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddSensor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        AddSensor.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 30));

        jLabel1.setText("Latitude");
        AddSensor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, 30));
        AddSensor.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, 30));

        jLabel2.setText("Add Field");
        AddSensor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 50));

        jLabel4.setText("Field Id");
        AddSensor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, 30));
        AddSensor.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        AddSensor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, 290));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        AddSensor.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 80, -1));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        AddSensor.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        jLabel7.setText("Farmer");
        AddSensor.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 70, 30));

        jLabel11.setText("Crop");
        AddSensor.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 70, 30));

        jLabel12.setText("Location");
        AddSensor.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 70, 30));

        jLabel13.setText("Longitude");
        AddSensor.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, 30));
        AddSensor.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, 30));

        AddSensor.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 200, 30));

        AddSensor.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 200, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/grass_PNG401.png"))); // NOI18N
        AddSensor.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        jTabbedPane1.addTab("Add Field", AddSensor);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 540, 290));

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 80, -1));

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel8.setText("Edit Corp");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 50));

        jLabel14.setText("Field Id");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, 30));
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 30));

        jLabel15.setText("Latitude");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, 30));
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, 30));

        jLabel16.setText("Longitude");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, 30));
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, 30));

        jLabel17.setText("Location");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 70, 30));
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 30));
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 70, 30));
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 70, 30));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/grass_PNG401.png"))); // NOI18N
        jPanel3.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        jTabbedPane1.addTab("Edit Field", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 80, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 540, 290));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 160, 50));

        jLabel10.setText("Dekete Crop");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 50));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/grass_PNG401.png"))); // NOI18N
        jPanel4.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1000, 600));

        jTabbedPane1.addTab("Delete Field", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id = Integer.parseInt(jTextField1.getText());
        double longe = Double.parseDouble(jTextField9.getText().toString());
        double lati = Double.parseDouble(jTextField2.getText().toString());
        String location = jTextField3.getText().toString();
        int ownerid = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        int cropid = Integer.parseInt(jComboBox2.getSelectedItem().toString());

        if (jTextField1.getText().isEmpty() | jTextField2.getText().isEmpty() | jTextField3.getText().isEmpty() | jTextField9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill up the fields.");
        } else {
            Farmer owner = sou.getFarmerById(ownerid);
            Crop cp = soc.findCropById(cropid);
            Field fd = new Field(id, lati, longe, location, owner, cp);
            sof.addField(fd);

            try {
                sof.serialize();
                JOptionPane.showMessageDialog(rootPane, "Field successfully Added");

                sof.deSerialize();
                fieldTableLoad(sof, jTable1, jScrollPane1);
                fieldTableLoad(sof, jTable2, jScrollPane2);
                fieldTableLoad(sof, jTable3, jScrollPane3);

                jTextField1.setText(null);
                jTextField2.setText(null);
                jTextField3.setText(null);
                jTextField9.setText(null);
            } catch (Exception e1) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField9.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int r = jTable2.getSelectedRow();
        jTextField7.setText(jTable2.getValueAt(r, 0).toString());
        jTextField8.setText(jTable2.getValueAt(r, 2).toString());
        jTextField10.setText(jTable2.getValueAt(r, 3).toString());
        jTextField11.setText(jTable2.getValueAt(r, 1).toString());
        jLabel18.setText(jTable2.getValueAt(r, 4).toString());
        jLabel19.setText(jTable2.getValueAt(r, 5).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTextField7.getText().isEmpty() | jTextField8.getText().isEmpty() | jTextField10.getText().isEmpty() | jTextField11.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill up the fields.");
        } else {
            int fieldid = Integer.parseInt(jTextField7.getText());
            double longe = Double.parseDouble(jTextField8.getText().toString());
            double lati = Double.parseDouble(jTextField10.getText().toString());
            String location = jTextField11.getText().toString();
            String oname = jLabel18.getText().toString();
            String cname = jLabel19.getText().toString();
            Farmer owner = sou.getFarmerByName(oname);
            Crop cp = soc.findCropByName(cname);
            
            sof.removeField(sof.findFieldById(fieldid));

            Field fd = new Field(fieldid, longe, lati, location, owner, cp);
            sof.addField(fd);

            try {

                sof.serialize();
                JOptionPane.showMessageDialog(rootPane, "Field successfully Eddited");

                soc.deserialize();
                fieldTableLoad(sof, jTable1, jScrollPane1);
                fieldTableLoad(sof, jTable2, jScrollPane2);
                fieldTableLoad(sof, jTable3, jScrollPane3);

                jTextField7.setText(null);
                jTextField8.setText(null);
                jTextField10.setText(null);
                jTextField11.setText(null);
            } catch (Exception e1) {
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField7.setText(null);
        jTextField8.setText(null);
        jTextField10.setText(null);
        jTextField11.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int id = Integer.parseInt(jLabel9.getText());

        int x = JOptionPane.showConfirmDialog(rootPane, "Are you sure?");

        if (x == 0) {
            sof.remove(sof.findFieldById(id));

            try {

                sof.serialize();
                JOptionPane.showMessageDialog(rootPane, "Field successfully Deleted");

                soc.deserialize();
                fieldTableLoad(sof, jTable1, jScrollPane1);
                fieldTableLoad(sof, jTable2, jScrollPane2);
                fieldTableLoad(sof, jTable3, jScrollPane3);
            } catch (Exception e1) {
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int r = jTable3.getSelectedRow();
        jLabel9.setText(jTable3.getValueAt(r, 0).toString());
    }//GEN-LAST:event_jTable3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FieldManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FieldManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FieldManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FieldManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FieldManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddSensor;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
