/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.Desktop;

import javax.swing.JOptionPane;
import Users.Farmer;
import Users.Manager;
import serialization.Serialization;
import Users.setOfUsers;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gsark
 */
public class MainUI extends javax.swing.JFrame {

    private setOfUsers sou = new setOfUsers();

    /**
     * Creates new form Login
     */
    public MainUI() {
        try {
            sou.deserialize();
        } catch (Exception e) {
        }

        initComponents();

        TopPanel.removeAll();
        TopPanel.repaint();
        TopPanel.revalidate();
        //aaaaaaaa
        TopPanel.add(LoginPanel);
        TopPanel.repaint();
        TopPanel.revalidate();

        userTableLoad(sou, jTable1, jScrollPane1);
        userTableLoad(sou, jTable2, jScrollPane2);
        userTableLoad(sou, jTable3, jScrollPane3);
    }

    /**
     * Use to load user details in a table in edit tab
     *
     * @param users
     */
    /*public void userTableLoad(setOfUsers users, JTable table, JScrollPane pane) {
        Vector tmp = new Vector<>();
        Vector<Farmer> far = users.getAllFarmers();

        System.out.println(users.getAllFarmers());

        for (Farmer fm : far) {
            Vector row = new Vector();
            row.addElement(fm.getUserId());
            row.addElement(fm.getName());
            row.addElement(fm.getUsername());
            row.addElement(fm.getEmail());
            row.addElement(fm.getType());

            tmp.add(row);
        }
        //set column headings
        Vector columnNames = new Vector();
        columnNames.addElement("User ID");
        columnNames.addElement("Name");
        columnNames.addElement("email");
        columnNames.addElement("Username");
        columnNames.addElement("User Type");
        //set table model
        DefaultTableModel model = new DefaultTableModel(tmp, columnNames);

        table.setModel(model);
        pane.setViewportView(table);
        table.setAutoscrolls(true);
        table.getTableHeader().setReorderingAllowed(false);
    }*/
    
    public void userTableLoad(setOfUsers users, JTable table, JScrollPane pane) {
        Vector tmp = new Vector<>();
        Vector<Farmer> far = users.getAllFarmers();
        Vector<Manager> man = users.getAllManagers();

        for (Farmer fm : far) {
            Vector row = new Vector();
            row.addElement(fm.getUserId());
            row.addElement(fm.getName());
            row.addElement(fm.getUsername());
            row.addElement(fm.getEmail());
            row.addElement(fm.getType());

            tmp.add(row);
        }
        
        for (Manager mn : man) {
            Vector row = new Vector();
            row.addElement(mn.getUserId());
            row.addElement(mn.getName());
            row.addElement(mn.getUsername());
            row.addElement(mn.getEmail());
            row.addElement(mn.getType());

            tmp.add(row);
        }
        //set column headings
        Vector columnNames = new Vector();
        columnNames.addElement("User ID");
        columnNames.addElement("Name");
        columnNames.addElement("email");
        columnNames.addElement("Username");
        columnNames.addElement("User Type");
        //set table model
        DefaultTableModel model = new DefaultTableModel(tmp, columnNames);

        table.setModel(model);
        pane.setViewportView(table);
        table.setAutoscrolls(true);
        table.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        MainMenu = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        UserManagement = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AddUser = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_add_name = new javax.swing.JTextField();
        txt_add_email = new javax.swing.JTextField();
        txt_add_username = new javax.swing.JTextField();
        cmb_add_type = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_adduser = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txt_add_password = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        EditUser = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_edit_username = new javax.swing.JTextField();
        txt_edit_email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_edit_type = new javax.swing.JLabel();
        lbl_edit_name = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        DeleteUser = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_delete_name = new javax.swing.JLabel();
        lbl_delete_type = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopPanel.setBackground(new java.awt.Color(255, 255, 255));
        TopPanel.setLayout(new java.awt.CardLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        LoginPanel.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 160, 280, 30));
        LoginPanel.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 280, 30));

        btn_login.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        btn_login.setForeground(new java.awt.Color(102, 102, 102));
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        LoginPanel.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 160, 30));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Use Name");
        LoginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 80, 20));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Password");
        LoginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 80, 20));

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/grass_PNG401.png"))); // NOI18N
        LoginPanel.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        TopPanel.add(LoginPanel, "card2");

        MainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/UserManagement.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/UserManagementZoom.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        MainMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 190, 190));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/FieldStationManagement.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/FieldStationManagementZoom.png"))); // NOI18N
        MainMenu.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 330, 180));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/FieldManagement.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/FieldManagementZoom.png"))); // NOI18N
        MainMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 330, 180));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/SensorManagment.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/SensorManagmentZoom.png"))); // NOI18N
        MainMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 190, 180));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/crop1.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/Crop 2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        MainMenu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 180, 180));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/Logout.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/LogoutZoom.png"))); // NOI18N
        MainMenu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 180, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/CSSD Menu.jpg"))); // NOI18N
        MainMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        TopPanel.add(MainMenu, "card3");

        UserManagement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddUser.setBackground(new java.awt.Color(255, 255, 255));
        AddUser.setPreferredSize(new java.awt.Dimension(1000, 620));
        AddUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Add User To the System");
        AddUser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 60));
        AddUser.add(txt_add_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 280, 30));
        AddUser.add(txt_add_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 280, 30));

        txt_add_username.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        txt_add_username.setForeground(new java.awt.Color(102, 102, 102));
        AddUser.add(txt_add_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 280, 30));

        cmb_add_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Farmer", "Food Processing Manager" }));
        AddUser.add(cmb_add_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 280, 30));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Name");
        AddUser.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, 30));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("E-Mail");
        AddUser.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, 30));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Username");
        AddUser.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, 30));

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Password");
        AddUser.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, 30));

        btn_adduser.setText("ADD USER");
        btn_adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adduserActionPerformed(evt);
            }
        });
        AddUser.add(btn_adduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 120, 30));

        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        AddUser.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 120, 30));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        AddUser.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 370));

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("User Type");
        AddUser.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, 30));
        AddUser.add(txt_add_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 280, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/grass_PNG401.png"))); // NOI18N
        AddUser.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        jTabbedPane1.addTab("Add User", AddUser);

        EditUser.setBackground(new java.awt.Color(255, 255, 255));
        EditUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Edit User ");
        EditUser.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        EditUser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 700, 170));

        jButton7.setText("Save");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        EditUser.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, -1));

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("User Type");
        EditUser.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 80, 30));
        EditUser.add(txt_edit_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 280, 30));
        EditUser.add(txt_edit_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 280, 30));

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Username");
        EditUser.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 80, 30));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Email");
        EditUser.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 80, 30));

        lbl_edit_type.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditUser.add(lbl_edit_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 280, 30));

        lbl_edit_name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditUser.add(lbl_edit_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 280, 30));

        jButton10.setText("Reset");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        EditUser.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Name");
        EditUser.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 80, 30));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/grass_PNG401.png"))); // NOI18N
        EditUser.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));

        jTabbedPane1.addTab("Edit User", EditUser);

        DeleteUser.setBackground(new java.awt.Color(255, 255, 255));
        DeleteUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        DeleteUser.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 700, 300));

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        DeleteUser.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Delete User ");
        DeleteUser.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 60));

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Selected");
        DeleteUser.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 120, 30));
        DeleteUser.add(lbl_delete_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 120, 30));
        DeleteUser.add(lbl_delete_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 140, 30));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Desktop/Images/grass_PNG401.png"))); // NOI18N
        DeleteUser.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 570));

        jTabbedPane1.addTab("Delete User", DeleteUser);

        UserManagement.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        TopPanel.add(UserManagement, "card5");

        getContentPane().add(TopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String username = txt_username.getText().toString();
        String password = txt_password.getText().toString();

        if (txt_username.getText().isEmpty() | txt_password.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill up the fields.");
        } else if (username.equals("admin") && password.equals("admin")) {
            TopPanel.removeAll();
            TopPanel.repaint();
            TopPanel.revalidate();
            //aaaaaaaa
            TopPanel.add(MainMenu);
            TopPanel.repaint();
            TopPanel.revalidate();
        } else {
            JOptionPane.showMessageDialog(LoginPanel, "Username or Password Invalid.");
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TopPanel.removeAll();
        TopPanel.repaint();
        TopPanel.revalidate();
        //aaaaaaaa
        TopPanel.add(UserManagement);
        TopPanel.repaint();
        TopPanel.revalidate();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adduserActionPerformed

        String name = txt_add_name.getText().toString();
        String email = txt_add_email.getText().toString();
        String username = txt_add_username.getText().toString();
        String password = txt_add_password.getText().toString();
        String type = cmb_add_type.getSelectedItem().toString();

        if (txt_add_name.getText().isEmpty() | txt_add_email.getText().isEmpty() | txt_add_username.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill up the fields.");
        }else{
            if (type.equalsIgnoreCase("Farmer")) {
                Farmer fm = new Farmer(name, username, email, password, type);
                sou.addFarmer(fm);

                try {
                    sou.serialize();
                    JOptionPane.showMessageDialog(rootPane, "User successfully Added");

                    sou.deserialize();
                    userTableLoad(sou, jTable1, jScrollPane1);
                    userTableLoad(sou, jTable2, jScrollPane2);
                    userTableLoad(sou, jTable3, jScrollPane3);

                    txt_add_name.setText(null);
                    txt_add_email.setText(null);
                    txt_add_username.setText(null);
                } catch (Exception e1) {
                }
            } else if (type.equalsIgnoreCase("Food Processing Manager")) {
                Manager mn = new Manager(name, username, email, password, type);
                sou.addManager(mn);

                try {
                    sou.serialize();
                    JOptionPane.showMessageDialog(rootPane, "User successfully Added");

                    sou.deserialize();
                    userTableLoad(sou, jTable1, jScrollPane1);
                    userTableLoad(sou, jTable2, jScrollPane2);
                    userTableLoad(sou, jTable3, jScrollPane3);

                    txt_add_name.setText(null);
                    txt_add_email.setText(null);
                    txt_add_username.setText(null);
                } catch (Exception e1) {
                }
            }
        }
    }//GEN-LAST:event_btn_adduserActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        txt_add_name.setText(null);
        txt_add_email.setText(null);
        txt_add_username.setText(null);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable1.getSelectedRow();
        //get the member number of the selected row
        lbl_edit_name.setText(jTable1.getValueAt(r, 3).toString());
        txt_edit_username.setText(jTable1.getValueAt(r, 1).toString());
        txt_edit_email.setText(jTable1.getValueAt(r, 2).toString());
        lbl_edit_type.setText(jTable1.getValueAt(r, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String name = lbl_edit_name.getText().toString();
        String email = txt_edit_email.getText().toString();
        String username = txt_edit_username.getText().toString();
        String type = lbl_edit_type.getText().toString();

        if (txt_edit_email.getText().isEmpty() | txt_edit_username.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill up the fields.");
        } else{
            if (type.equalsIgnoreCase("Farmer")) {
                Farmer fmr = sou.getFarmerByName(name);
                String password = fmr.getPassword();
                sou.removeFarmer(fmr);

                Farmer fm = new Farmer(name, username, email, password, type);
                sou.addFarmer(fm);

                try {
                    sou.serialize();
                    JOptionPane.showMessageDialog(rootPane, "Successfully Saved");

                    sou.deserialize();
                    userTableLoad(sou, jTable1, jScrollPane1);
                    userTableLoad(sou, jTable2, jScrollPane2);
                    userTableLoad(sou, jTable3, jScrollPane3);

                    lbl_edit_name.setText(null);
                    txt_edit_email.setText(null);
                    txt_edit_username.setText(null);
                    lbl_edit_type.setText(null);
                } catch (Exception e1) {
                }
            } else if (type.equalsIgnoreCase("Food Processing Manager")) {
                Manager mnr = sou.getManagerByName(name);
                String password = mnr.getPassword();
                sou.removeManager(mnr);

                Manager mn = new Manager(name, username, email, password, type);
                sou.addManager(mn);

                try {
                    sou.serialize();
                    JOptionPane.showMessageDialog(rootPane, "Successfully Saved");

                    sou.deserialize();
                    userTableLoad(sou, jTable1, jScrollPane1);
                    userTableLoad(sou, jTable2, jScrollPane2);
                    userTableLoad(sou, jTable3, jScrollPane3);

                    lbl_edit_name.setText(null);
                    txt_edit_email.setText(null);
                    txt_edit_username.setText(null);
                    lbl_edit_type.setText(null);
                } catch (Exception e1) {
                }
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String name = lbl_delete_name.getText().toString();
        String type = lbl_delete_type.getText().toString();

        int x = JOptionPane.showConfirmDialog(rootPane, "Are you sure about this?");
        System.out.println(x);
        
        if (x == 0) {
            if (type.equalsIgnoreCase("Farmer")) {
                Farmer fmr = sou.getFarmerByName(name);
                sou.removeFarmer(fmr);

                try {
                    sou.serialize();
                    JOptionPane.showMessageDialog(rootPane, "Successfully Delete");

                    sou.deserialize();
                    userTableLoad(sou, jTable1, jScrollPane1);
                    userTableLoad(sou, jTable2, jScrollPane2);
                    userTableLoad(sou, jTable3, jScrollPane3);
                } catch (Exception e1) {
                }
            } else if (type.equalsIgnoreCase("Food Processing Manager")) {
                Manager mnr = sou.getManagerByName(name);
                sou.removeManager(mnr);

                try {
                    sou.serialize();
                    JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");

                    sou.deserialize();
                    userTableLoad(sou, jTable1, jScrollPane1);
                    userTableLoad(sou, jTable2, jScrollPane2);
                    userTableLoad(sou, jTable3, jScrollPane3);
                } catch (Exception e1) {
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "bla bla bla");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int r = jTable2.getSelectedRow();
        lbl_delete_name.setText(jTable2.getValueAt(r, 1).toString());
        lbl_delete_type.setText(jTable2.getValueAt(r, 4).toString());

    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        lbl_edit_name.setText(null);
        txt_edit_email.setText(null);
        txt_edit_username.setText(null);
        lbl_edit_type.setText(null);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddUser;
    private javax.swing.JPanel DeleteUser;
    private javax.swing.JPanel EditUser;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel UserManagement;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JButton btn_adduser;
    private javax.swing.JButton btn_login;
    private javax.swing.JComboBox<String> cmb_add_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl_delete_name;
    private javax.swing.JLabel lbl_delete_type;
    private javax.swing.JLabel lbl_edit_name;
    private javax.swing.JLabel lbl_edit_type;
    private javax.swing.JTextField txt_add_email;
    private javax.swing.JTextField txt_add_name;
    private javax.swing.JTextField txt_add_password;
    private javax.swing.JTextField txt_add_username;
    private javax.swing.JTextField txt_edit_email;
    private javax.swing.JTextField txt_edit_username;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

}
